# Generated by Django 4.1 on 2024-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('session_id', models.IntegerField(null=True)),
                ('module', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audits',
            },
        ),
    ]
