# Generated by Django 4.1 on 2024-06-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
